package:
    name: non-linear-shrinkage
    version: 1.0.0

source:
    path: ..

build:
    number: 0
    noarch: python

requirements:
    build:
        - python
        - pytest
        - numpy
    run:
        - python
        - numpy
